spring.application.name=metrics-processor

server.port=8082

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=metrics-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

influxdb.url=http://localhost:8086
influxdb.token=SNsai8n_CUsAzS3nIw4xcvknMPo2jGrzi4Pa33CRI3q_PfRwZqHAwrRs5t0hAkhZ9iTDsLdXTbJKs96efk9OGw==
influxdb.org=metrics-org
influxdb.bucket=metrics